# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cuda_sim_BS_call <- function(S, H, E, r, sigma, Nsample) {
    .Call(`_finsim_cuda_sim_BS_call`, S, H, E, r, sigma, Nsample)
}

cuda_sim_JDP_GPU <- function(H, r, sigma, lambda_jump, mu_jump, sigma_jump, dt, Nsample) {
    .Call(`_finsim_cuda_sim_JDP_GPU`, H, r, sigma, lambda_jump, mu_jump, sigma_jump, dt, Nsample)
}

